name: Build and release

permissions:
  contents: write
  actions: write
  checks: write
  deployments: write
  issues: write
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write
  
on:
  push:
    tags:
      - '*'

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest  

    env:
      Solution_Name: AutoTf.YubiKeyInteractor.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: Publish
      run: dotnet publish -c Release -r win-x64 --self-contained true --output ./publish/windows
      
    - name: Build MacOs
      run: dotnet publish -c Release -r osx-x64 --self-contained true -o ./publish/macos

    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v4
      with:
        name: win-x64
        path: ./publish/windows

    - name: Upload macOS Artifact
      uses: actions/upload-artifact@v4
      with:
        name: osx-x64
        path: ./publish/macos

  release:
      needs: build
      runs-on: ubuntu-latest
      
      steps:
        - name: Download Windows Artifact
          uses: actions/download-artifact@v4
          with:
            name: win-x64
            path: ./win-x64
            
        - name: Download macOS Artifact
          uses: actions/download-artifact@v4
          with:
            name: osx-x64
            path: ./osx-x64
  
        - name: Zip artifacts
          run: |
            zip -r win-x64.zip ./win-x64
            zip -r macos-x64.zip ./osx-x64
  
        - name: Create GitHub Release
          uses: softprops/action-gh-release@v2
          with:
            files: |
              win-x64.zip
              macos-x64.zip
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
